//the root layout is applied to all routes.

import NavBar from "@/components/NavBar";

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

//exported metadata will appear in the <head> section
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//the root layout must define <html> and <body>tags since Next.js doesn't automatically create them.
//All layouts support nesting via children prop
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}

// View the source of http://localhost:3000 and /about and match the HTML structure back to the layout files

// ++ Modify the metadata and try to change fonts
// https://nextjs.org/docs/app/building-your-application/optimizing/fonts#google-fonts
